### PR TITLE
Ignore null values when decoding JSON

### PR DESCRIPTION
**Pull request by anjannath**

### CODE REVIEW

**Comment by guillaumerose** [comment]
lgtm, I have a fix in my PR for the sleep at startup.

**Comment by guillaumerose** [comment]
I added the missing handler https://github.com/code-ready/tray-windows/pull/85/files#diff-d321e6c10e14601e27b4840363160e8ccf82dd7fe4aef9d76b6c282914ae782eR79

lgtm!

**Comment by guillaumerose** [comment]
I still see the exception when start result is an error and it tries to decode it as a working start result.

**Comment by anjannath** [comment]
> 
> 
> I still see the exception when start result is an error and it tries to decode it as a working start result.

This is fixed in #87 ?

**Comment by guillaumerose** [comment]
It fixes for me the exception when start is ending with an error.

**Pull request closed without merging**
